// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define src_Course_BODY

/************************************************************
 Course class body
 ************************************************************/

// include associated header file
#include "src/Course.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of Course class body
 ************************************************************/
