// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SRC_COURSE_H
#define SRC_COURSE_H

/************************************************************
 Course class header
 ************************************************************/

#include "src/Pkg_src.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

/************************************************************/
/**
 * 
 */
class Course {

	/**
	 * 
	 */
	::PrimitiveTypes::String course_name;
	/**
	 * 
	 */
	::PrimitiveTypes::Integer course_id;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Course class header
 ************************************************************/

#endif
