// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define src_Demand_BODY

/************************************************************
 Demand class body
 ************************************************************/

// include associated header file
#include "src/Demand.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of Demand class body
 ************************************************************/
