// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SRC_DEMAND_H
#define SRC_DEMAND_H

/************************************************************
 Demand class header
 ************************************************************/

#include "src/Pkg_src.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "src/Org.h"

/************************************************************/
/**
 * 
 */
class Demand {
public:
	/**
	 * 
	 */
	Org org;

private:
	/**
	 * 
	 */
	::PrimitiveTypes::Integer id;
	/**
	 * 
	 */
	::PrimitiveTypes::String description;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Demand class header
 ************************************************************/

#endif
