// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define src_Employee_BODY

/************************************************************
 Employee class body
 ************************************************************/

// include associated header file
#include "src/Employee.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of Employee class body
 ************************************************************/
