// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SRC_EMPLOYEE_H
#define SRC_EMPLOYEE_H

/************************************************************
 Employee class header
 ************************************************************/

#include "src/Pkg_src.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "src/User.h"

/************************************************************/
/**
 * 
 */
class Employee: public User {

	/**
	 * 
	 */
	::PrimitiveTypes::Integer SIAPE;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Employee class header
 ************************************************************/

#endif
