// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SRC_FORM_H
#define SRC_FORM_H

/************************************************************
 Form class header
 ************************************************************/

#include "src/Pkg_src.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "src/Demand.h"

/************************************************************/
/**
 * 
 */
class Form {
public:
	/**
	 * 
	 */
	Demand *demand;

private:
	/**
	 * 
	 */
	::PrimitiveTypes::Integer protocol;
	/**
	 * 
	 */
	::PrimitiveTypes::String informationDespachos;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Form class header
 ************************************************************/

#endif
