// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SRC_STUDENT_H
#define SRC_STUDENT_H

/************************************************************
 Student class header
 ************************************************************/

#include "src/Pkg_src.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "src/Course.h"
#include "src/User.h"

/************************************************************/
/**
 * 
 */
class Student: public User {
public:
	/**
	 * 
	 */
	Course course;

private:
	/**
	 * 
	 */
	::PrimitiveTypes::Integer admissionYear;
	/**
	 * 
	 */
	::PrimitiveTypes::Integer admissionSemester;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Student class header
 ************************************************************/

#endif
