// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define src_Student_BODY

/************************************************************
 Student class body
 ************************************************************/

// include associated header file
#include "src/Student.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of Student class body
 ************************************************************/
