// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define src_User_BODY

/************************************************************
 User class body
 ************************************************************/

// include associated header file
#include "src/User.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 * @param newCPF 
 */
void User::setCPF(::PrimitiveTypes::Integer /*in*/newCPF) {
}

/**
 * 
 * @return userCPF 
 */
::PrimitiveTypes::Integer User::getCPF() {
}

/************************************************************
 End of User class body
 ************************************************************/
