// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SRC_USER_H
#define SRC_USER_H

/************************************************************
 User class header
 ************************************************************/

#include "src/Pkg_src.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "src/Form.h"

/************************************************************/
/**
 * 
 */
class User {
public:
	/**
	 * 
	 */
	Form *form;

	/**
	 * 
	 * @param newCPF 
	 */
	void setCPF(::PrimitiveTypes::Integer /*in*/newCPF);

	/**
	 * 
	 * @return userCPF 
	 */
	::PrimitiveTypes::Integer getCPF();

private:
	/**
	 * 
	 */
	::PrimitiveTypes::Integer CPF;
	/**
	 * 
	 */
	::PrimitiveTypes::String name;
	/**
	 * 
	 */
	::PrimitiveTypes::String email;
	/**
	 * 
	 */
	::PrimitiveTypes::String address;
	/**
	 * 
	 */
	::PrimitiveTypes::Integer phoneNumber;
	/**
	 * 
	 */
	::PrimitiveTypes::String district;
	/**
	 * 
	 */
	::PrimitiveTypes::String state;
	/**
	 * 
	 */
	::PrimitiveTypes::String addressNumber;
	/**
	 * 
	 */
	::PrimitiveTypes::Integer postalCode;
	/**
	 * 
	 */
	::PrimitiveTypes::Integer phoneNumberArea;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of User class header
 ************************************************************/

#endif
